#!/usr/bin/bash
mv ${HOME}/.tmux.conf ${HOME}/.tmux.conf.bak
cp .tmux.conf ${HOME}/.tmux.conf
cd $HOME
mkdir -p local/.resurrect
conda install -y -p local -c conda-forge tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

echo '
## new tmux
export PATH="${HOME}/local/bin:$PATH"
## autostart tmux
function this_outside_tmux() { [ -z $TMUX ] }
function exist_detached_tmux_session(){ [[ $(tmux ls|wc -l) > $(tmux ls|grep -c attached) ]] }
function this_on_host() { [[ $HOSTNAME == ''#TODO ]] }
function query_allocated_node() {
  #TODO
  allocated=
}
function apply_for_allocation() {
  #TODE
  allocated=
}
function connect_to_node() {
  return [[ 1 > 0 ]]
  query_allocated_node
  if [ -n $allocated ];then
    apply_for_allocation
  fi
  ssh lutan@$allocated #TODO
}


## auto enter tmux and auto connect to node repeatedly
if this_outside_tmux;then
  if exist_detached_tmux_session; then
    tmux attach
  elif this_on_host;then
    tmux -L ${HOMENAME}
  else
    tmux
  fi
elif this_on_host;then
  while ! connect_to_node; do
    echo "try to auto reconnect $allocated "
  done
else
  echo -e "\033[31m You have connected to $HOSTNAME at $(date) \033[0m"
fi
' >> .bashrc


